[chore][internal/coreinternal] Fix compile error and skip test in strptime_cgo_test.go when using old glibc (#49516)
#### Description
Similarly to
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/49485,
when using glibc versions older than 2.19, `struct tm` doesn't have a
`tm_gmtoff` field by default, resulting in compilation errors.

```
Error:
    # github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/timeutils
/var/cache/dd/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.155.0/timeutils/strptime_cgo_testlib.go:34:36: tm.tm_gmtoff undefined (type _Ctype_struct_tm has no field or method tm_gmtoff)
/var/cache/dd/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.155.0/timeutils/strptime_cgo_testlib.go:48:3: unknown field tm_gmtoff in struct literal of type _Ctype_struct_tm
```

Defining `_BSD_SOURCE` (the ancestor of `_DEFAULT_SOURCE`, already
defined here) fixes the compilation issue.

Running the test still fails with old glibc or when using musl libc,
because they don't support some of the `%z` formats used in those tests
(`[+-]HH` vs `[+-]HHMM` vs `[+-]HH:MM` vs `Z`), so I also added a check
to skip the test when not using a recent glibc version.

Musl:
```
Error:        Received unexpected error:
              strptime failed to parse the whole string
Test:         TestParseStrptimeCgo/iso-8601-utc/2007-04-05T12:30:46+00:00
```

Glibc 2.17:
```
Error:        Received unexpected error:
              strptime failed to parse the whole string
Test:         TestParseStrptimeCgo/iso-8601-utc/2007-04-05T12:30:46Z

Error:        Received unexpected error:
              strptime failed to parse: remainder ":00"
Test:         TestParseStrptimeCgo/iso-8601-hst/2007-04-05T06:07:08-10:00
```

#### Testing
Validated on Linux using a recent glibc (compiles, runs, and passes), an
old glibc (skipped), and musl (skipped).

#### Authorship

- [x] I, a human, wrote this pull request description myself.